export default {
  type: "error",
  position: "bottom-center",
  timeout: 4000,
  closeOnClick: false,
  pauseOnFocusLoss: false,
  pauseOnHover: true,
  draggable: true,
  draggablePercent: 0.6,
  showCloseButtonOnHover: true,
  hideProgressBar: false,
  closeButton: true,
  icon: true,
  rtl: false,
};
